# Label PRs based on changed files
# Note: Categorization labels (documentation, tests, ci) are handled by
# conventional commit prefixes in PR titles via release-drafter autolabeler.
# Only organizational/component labels are applied here.

'core':
  - changed-files:
    - any-glob-to-any-file: 'src/flycatcher/base.py'

'fields':
  - changed-files:
    - any-glob-to-any-file: 'src/flycatcher/fields.py'

'validators':
  - changed-files:
    - any-glob-to-any-file: 'src/flycatcher/validators.py'

'generators':
  - changed-files:
    - any-glob-to-any-file: 'src/flycatcher/generators/**/*'

'dependencies':
  - changed-files:
    - any-glob-to-any-file: ['pyproject.toml', 'uv.lock']

