name: '🔧 Chore tracker'
description: Suggest maintenance, testing, and other non-feature work for flycatcher.
labels: maintenance

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a chore! Please fill in the form below.
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I have checked that this issue has not already been reported.
          required: true
        - label: I have confirmed this task is still relevant for the [latest version](https://pypi.org/project/flycatcher/) of flycatcher.
          required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of flycatcher are you using?
      options:
        - 0.1.0
      default: 0
  - type: textarea
    id: description
    attributes:
      label: What's the job?
      description: >
        Please describe the task / maintenance work you are suggesting.
      value: |
        <description>
    validations:
      required: true
